// categoriesData.js

const jobCategoryData = [
    "Graphics & Design",
    "Mobile App Development",
    "Frontend Web Development",
    "MERN Stack Development",
    "Account & Finance",
    "Artificial Intelligence",
    "Video Animation",
    "MEAN Stack Development",
    "MEVN Stack Development",
    "Data Entry Operator",
    "Desktop Development",
    "UI/UX Design",
    "Backend Development",
    "Customer Support",
    "Marketing",
    "Project Management",
    "E-commerce",
    "Software Testing",
    "Game Development",
    "Content Writing",
    "Digital Marketing",
    "Network Administration",
    "Database Management",
    "Virtual Reality",
    "Blockchain Development",
    "Social Media Management",
    "Legal Services",
    "Healthcare",
    "Music Production",
    "Photography",
    "Event Planning",
    "Data Analysis",
    "Education & Training",
    "Human Resources",
    "Sales",
    "Logistics",
    "Fashion Design",
    "Interior Design",
    "Food & Beverage",
    "Sports Coaching",
    "Journalism",
    "Public Relations",
    "Real Estate",
    "Travel & Tourism",
    "Fitness Training",
    "Automotive Services",
    "Construction Management",
    "Environmental Services",
    "Renewable Energy",
    "Graphic Design",
    "Legal Consulting",
    "Home Services",
    "Software Engineering",
    "Cybersecurity",
    "Supply Chain Management",
    "Telecommunications",
    "Health & Wellness",
    "Agriculture",
    "Entertainment",
    "Insurance",
    "Forex Trading",
    "Gardening & Landscaping",
    "Retail Management",
    "Animation",
    "Public Speaking",
    "Translation Services",
    "Investment Banking",
    "Aviation",
    "Chemical Engineering",
    "Mechanical Engineering",
    "Robotics",
    "Culinary Arts",
    "Welding & Fabrication",
    "Fashion Styling",
    "Video Production",
    "Architectural Design",
    "Music Composition",
    "Sustainable Development",
    "Legal Writing",
    "Supply Chain Consulting",
    "Fitness Instruction",
    "Behavioral Psychology",
    "Pet Care",
    "Marine Biology",
    "Dental Services",
    "Renovation Services",
    "Beauty Therapy",
    "Childcare",
    "Luxury Goods",
    "Textile Design",
    "Financial Planning",
    "Podcasting",
    "Nonprofit Management",
    "Fitness Equipment",
    "Alternative Medicine",
    "Criminal Justice",
    "Meteorology",
    "Music Therapy",
    "Engineering Consulting",
    "Customer Experience",
    "Veterinary Services",
    "Nutrition Consulting",
    "Yoga Instruction",
    "Community Development",
    "Urban Planning",
    "Fine Arts",
    "Forensic Science",
    "Gaming Industry",
    "Event Management",
    "Legal Translation",
    "Financial Analysis",
    "Dance Instruction",
    "Social Work",
    "Sustainability Consulting",
    "Automotive Design",
    "Textile Production",
    "Podiatry",
    "Interior Decorating",
    "Fitness Modeling",
    "Mental Health Counseling",
    "Wedding Planning",
    "Video Editing",
    "Animal Care",
    "Machine Learning",
    "Environmental Engineering",
    "Business Coaching",
    "Legal Research",
    "Financial Management",
    "Guitar Instruction",
    "Corporate Training",
    "Public Health",
    "Modeling",
    "Language Teaching",
    "Business Intelligence",
    "Film Production",
    "Elderly Care",
    "Tattoo Artistry",
    "Art Restoration",
    "Sports Management",
    "Legal Advocacy",
    "Financial Technology",
    "HR Consulting",
    "Fitness Apparel",
    "Community Outreach",
    "Urban Farming",
    "Adventure Tourism",
    "Game Design",
    "Virtual Assistance",
    "Career Counseling",
    "Online Education",
    "Legal Mediation",
    "Risk Management",
    "Fitness Consulting",
    "Behavioral Therapy",
    "Cognitive Science",
    "Pet Training",
    "Martial Arts Instruction",
    "Event Photography",
    "Music Education",
    "Civil Engineering",
    "Dermatology",
    "Historical Research",
    "Fine Dining",
    "Luxury Travel",
    "Robotics Engineering",
    "Life Coaching",
    "Maritime Services",
  ];
  
  export default jobCategoryData;
  